### ISSUE TITLE
doesn´t use up bone meal

### ISSUE THREAD

**Issue by VBrieden** [Fuzss/universalbonemeal-fabric#1]
When using any of the new bone meal features of this mod in survival mode, no bone meal actually gets used up, leading to free item duplication.

tested in 1.18.2 with only version 3.0.2 of the mod and modmenu
![2022-04-09_21 30 32](https://user-images.githubusercontent.com/80428153/162589268-25ae6098-21d6-448b-85d5-dc6afbd13c7d.png)

**Comment by Fuzss** [comment]
Fixed in v3.0.4, thanks for reporting!
