### ISSUE TITLE
Compatibility with Fertilization and other

### ISSUE THREAD

**Issue by ardissaps** [Fuzss/universalbonemeal-fabric#2]
Does it compatible with [Fertilization](https://www.curseforge.com/minecraft/mc-mods/fertilization-fabric)?

and others such as croptopia farmer delight

**Comment by Fuzss** [comment]
No, there is no special compat for any mods. 

If you want a unique bone meal behavior for a modded crop I'd recommend contacting the mod author so that they can add the behavior directly to their mod.
